# Run test matrix on Pull Requests
#
# ==============================================================================
#
# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby    EOL
# PE 2021.Y     7.x      2.7     Quarterly updates
#
# https://puppet.com/docs/pe/latest/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# ==============================================================================
#
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
#

name: PR Tests
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  ruby-style:
    if: false # TODO Modules will need: rubocop in Gemfile, .rubocop.yml
    name: 'Ruby Style (experimental)'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
      - name: "Install Ruby ${{matrix.puppet.ruby_version}}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.8
          bundler-cache: true
      - run: |
          bundle show
          bundle exec rake rubocop
  releng-checks:
    name: 'RELENG checks'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: 'Install Ruby ${{matrix.puppet.ruby_version}}'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.8
          bundler-cache: true
      - run: 'command -v rpm || if command -v apt-get; then sudo apt-get update; sudo apt-get install -y rpm; fi ||:'
      - name: 'Tags and changelogs'
        run: |
          bundle exec rake pkg:check_version
          bundle exec rake pkg:compare_latest_tag
          bundle exec rake pkg:create_tag_changelog

  spec-tests:
    name: 'Puppet Spec'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        puppet:
          - label: 'Puppet 7.x'
            puppet_version: '~> 7.0'
            ruby_version: '2.7'
          - label: 'Puppet 8.x'
            puppet_version: '~> 8.0'
            ruby_version: '3.2'
    env:
      PUPPET_VERSION: '${{matrix.puppet.puppet_version}}'
    steps:
      - uses: actions/checkout@v6
      - name: 'Install Ruby ${{matrix.puppet.ruby_version}}'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.puppet.ruby_version}}
          bundler-cache: true
      # unit test uses mkisofs and rpmbuild
      - run: 'command -v mkisofs || if command -v apt-get; then sudo apt-get update; sudo apt-get install -y genisoimage; fi ||:'
      - run: 'command -v rpmbuild || if command -v apt-get; then sudo apt-get update; sudo apt-get install -y rpm-build; fi ||:'
      - run: 'command -v createrepo || if command -v apt-get; then sudo apt-get update; sudo apt-get install -y createrepo; fi ||:'
      - run: 'bundle exec rake spec'

#  dump_contexts:
#    name: 'Examine Context contents'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Dump contexts
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
#
